actors: 
  FORTE:
    image_url: /images/actors/FORTE.jpg
    name: FORTE
    url: https://twitter.com/FORTEgp05
  Dhj_NF:
    image_url: /images/actors/Dhj_NF.jpg
    name: ã˜ã‚ƒã‚Œã¿ãƒ¼
    url: https://twitter.com/Dhj_NF
  kuwahara_jsri:
    image_url: /images/actors/kuwahara_jsri.jpg
    name: ãã‚ã¯ã‚‰
    url: https://twitter.com/kuwahara_jsri
  anchor_cable:
    image_url: /images/actors/anchor_cable.jpg
    name: è„±è„‚ç¶¿
    url: https://twitter.com/anchor_cable
  hekitter:
    image_url: /images/actors/hekitter.jpg
    name: hekitter
    url: https://twitter.com/hekitter
  MzRyuKa:
    image_url: /images/actors/MzRyuKa.PNG
    name: ã¿ãšã‚Šã‚…
    url: https://twitter.com/MzRyuKa
  oyakata2438:
    image_url: /images/actors/oyakata2438.jpg
    name: ãŠã‚„ã‹ãŸ
    url: https://twitter.com/oyakata2438
  akrolayer:
    image_url: /images/actors/akrolayer.jpg
    name: ã”ã¾ãªã¤
    url: https://twitter.com/akrolayer
  gulDra_cranch:
    image_url: /images/actors/gulDra_cranch.png
    name: ããƒ¼ã©ã‚‰ãã‚‰ã‚“ã¡
    url: https://twitter.com/gulDra_cranch
  yk_ichinomiya:
    image_url: /images/actors/yk_ichinomiya.jpg
    name: ã‚†ãã•ã‚“
    url: https://twitter.com/yk_ichinomiya
  setoazusa:
    image_url: /images/actors/setoazusa.jpg
    name: ã›ã¨ã‚ãš
    url: https://twitter.com/setoazusa
  erukiti:
    image_url: /images/actors/erukiti.jpg
    name: ãˆã‚‹ãã¡
    url: https://twitter.com/erukiti
  kondoyuko:
    image_url: /images/actors/kondoyuko.jpg
    name: kondoyuko
    url: https://twitter.com/kondoyuko
  youchan:
    image_url: /images/actors/youchan.jpg
    name: ã‚ˆã†
    url: https://twitter.com/youchan
  mamy1326:
    image_url: /images/actors/mamy1326.jpg
    name: ã¾ã¿ãƒ¼
    url: https://twitter.com/mamy1326
  higuyume:
    image_url: /images/actors/higuyume.jpg
    name: KANE
    url: https://twitter.com/higuyume
  edamametsubu318:
    image_url: /images/actors/edamametsubu318.jpg
    name: ãšã‚“ã ã¾ã‚‹(ä»®)
    url: https://twitter.com/zuncha318
  a_w_a_n_a:
    image_url: /images/actors/a_w_a_n_a.jpg
    name: ã‚ã‚ãª
    url: https://twitter.com/awa_kuri23
  3s_hv:
    image_url: /images/actors/3s_hv.jpg
    name: VTRyo
    url: https://twitter.com/3s_hv
  arakawa_gios:
    image_url: /images/actors/arakawa_gios.png
    name: Taku
    url: https://twitter.com/arakawa_gios
  nagashi_ma_w:
    image_url: /images/actors/nagashi_ma_w.jpg
    name: ãªãŒã—ãƒ¼
    url: https://twitter.com/nagashi_ma_w
  yahsan2:
    image_url: /images/actors/yahsan2.jpg
    name: ã¿ã‚„ã‚‚ã¨
    url: https://twitter.com/yahsan2
  tkobayashi03:
    image_url: /images/actors/tkobayashi03.jpg
    name: tkobayashi
    url: https://twitter.com/tkobayashi03
  ebichiki:
    image_url: /images/actors/ebichiki.png
    name: ãˆã³ã¡ã
    url: https://twitter.com/ebichiki
  hmatsu47:
    image_url: /images/actors/hmatsu47.jpg
    name: ã¾ã¤
    url: https://twitter.com/hmatsu47
  amarelo_n24:
    image_url: /images/actors/amarelo_n24.jpg
    name: amarelo
    url: https://twitter.com/amarelo_n24
  goodengineer7:
    image_url: /images/actors/goodengineer7.jpg
    name: S(ã‚¨ã‚¹)
    url: https://twitter.com/goodengineer7
  iwasiman:
    image_url: /images/actors/iwasiman.jpg
    name: ã„ã‚ã—ã¾ã‚“
    url: https://twitter.com/iwasiman
  shucho0103:
    image_url: /images/actors/shucho0103.jpg
    name: ã—ã‚…ã†ã„ã¡ã‚
    url: https://twitter.com/shucho0103
  kobayashi_tech:
    image_url: /images/actors/kobayashi_tech.jpg
    name: ã‚³ãƒãƒ¤ã‚· ãƒªãƒ§ã‚¦ã‚¿
    url: https://twitter.com/kobayashi_tech
  ariaki4dev:
    image_url: /images/actors/ariaki4dev.jpg
    name: ariaki
    url: https://twitter.com/ariaki4dev
  ykokubo09:
    image_url: /images/actors/ykokubo09.jpg
    name: ykokubo09
    url: https://twitter.com/ykokubo09
  nemu1986:
    image_url: /images/actors/nemu1986.jpg
    name: nemu1986
    url: https://twitter.com/nemu1986
  mottox2:
    image_url: /images/actors/mottox2.jpg
    name: mottox2
    url: https://twitter.com/mottox2
  sapi_kawahara:
    image_url: /images/actors/sapi_kawahara.jpg
    name: sapi_kawahara
    url: https://twitter.com/sapi_kawahara
  komacchi_u:
    image_url: /images/actors/komacchi_u.jpg
    name: komacchi_u
    url: https://twitter.com/komacchi_u
  Ys_yu:
    image_url: /images/actors/Ys_yu.jpg
    name: Ys_yu
    url: https://twitter.com/Ys_yu
  yunon_phys:
    image_url: /images/actors/yunon_phys.jpg
    name: yunon_phys
    url: https://twitter.com/yunon_phys
  ihirhs:
    image_url: /images/actors/ihirhs.jpg
    name: ihirhs
    url: https://twitter.com/ihirhs
  zucky_zakizaki:
    image_url: /images/actors/zucky_zakizaki.jpg
    name: zucky_zakizaki
    url: https://twitter.com/zucky_zakizaki
  midono_ap1:
    image_url: /images/actors/midono_ap1.jpg
    name: midono_ap1
    url: https://twitter.com/midono_ap1
  inayamafumitaka:
    image_url: /images/actors/inayamafumitaka.png
    name: ã„ãªã‚„ã¾ãµã¿ãŸã‹
    url: https://twitter.com/inayamafumitaka
  ryuchan_00:
    image_url: /images/actors/ryuchan_00.jpg
    name: ãƒœãƒˆãƒ ã‚º
    url: https://twitter.com/ryuchan_00
  okash1n:
    image_url: /images/actors/okash1n.jpg
    name: ãŠã‹ã—ã‚“
    url: https://twitter.com/okash1n
  piyoon:
    image_url: /images/actors/piyoon.jpg
    name: å¡šåŸæ¸…æ–‡
    url: https://twitter.com/piyoon
  Shun_sgi:
    image_url: /images/actors/Shun_sgi.jpg
    name: Shun
    url: https://twitter.com/Shun_sgi
  sugya_pm:
    image_url: /images/actors/sugya_pm.jpg
    name: ã™ãã‚ƒ(â•¹â—¡â•¹)
    url: https://twitter.com/sugya_pm
  nilfigo:
    image_url: /images/actors/nilfigo.png
    name: nilfigo
    url: https://twitter.com/nilfigo
  sour23:
    image_url: /images/actors/sour23.jpg
    name: å¤§æ¾¤ æ–‡å­
    url: https://twitter.com/sour23
  amarelo:
    image_url: /images/actors/amarelo.jpg
    name: amarelo
    url: https://twitter.com/amarelo
  nano2_aloerina:
    image_url: /images/actors/nano2_aloerina.jpg
    name: ãªã®ãªã®
    url: https://twitter.com/nano2_aloerina
  viva_tweet_x:
    image_url: /images/actors/viva_tweet_x.jpg
    name: ã³ã°
    url: https://twitter.com/viva_tweet_x
  watanabeisan:
    image_url: /images/actors/watanabeisan.jpg
    name: ãªã¹ã•ã‚“
    url: https://twitter.com/watanabeisan
  fan_tech_:
    image_url: /images/actors/fan_tech_.jpg
    name: ãµãã‚“
    url: https://twitter.com/fan_tech_
  onigiri_:
    image_url: /images/actors/onigiri_.jpg
    name: onigiri Rice
    url: https://twitter.com/onigiri_
  jakelizzI:
    image_url: /images/actors/jakelizzI.jpg
    name: jakelizzI
    url: https://twitter.com/jakelizzI
  okutann88:
    image_url: /images/actors/okutann88.jpg
    name: okutann88
    url: https://twitter.com/okutann88
  fumiyasac:
    image_url: /images/actors/fumiyasac.jpg
    name: fumiyasac
    url: https://twitter.com/fumiyasac
  rhodium:
    image_url: /images/actors/rhodium.jpg
    name: ãƒ­ã‚¸ã‚¦ãƒ 
    url: https://twitter.com/_rhodium_
  uutan1108:
    image_url: /images/actors/uutan1108.jpg
    name: ã†ãƒ¼ãŸã‚“
    url: https://twitter.com/uutan1108
  rabspice:
    image_url: /images/actors/rabspice.jpg
    name: yugo.spice.ogura
    url: https://twitter.com/rabspice
  DAfurimacyan:
    image_url: /images/actors/DAfurimacyan.jpg
    name: ã‹ã‚ã®DA
    url: https://twitter.com/DAfurimacyan
  out_of_kaya:
    image_url: /images/actors/out_of_kaya.jpg
    name: ã±ã‚“ã ãŠã˜ã•ã‚“
    url: https://twitter.com/out_of_kaya
  petit_zome:
    image_url: /images/actors/petit_zome.jpg
    name: ã‚·ãƒ­
    url: https://twitter.com/petit_zome
  lsetzl_it:
    image_url: /images/actors/lsetzl_it.png
    name: ã›ã¤
    url: https://twitter.com/lsetzl_it
  lizhi05853:
    image_url: /images/actors/lizhi05853.jpg
    name: ã‚†ãƒ¼ã
    url: https://twitter.com/lizhi05853
  Sumirecheese:
    image_url: /images/actors/Sumirecheese.jpg
    name: SumireğŸ§€
    url: https://twitter.com/Sumirecheese
  G_OVER_N_GAME:
    image_url: /images/actors/G_OVER_N_GAME.jpg
    name: YUSUKEï½œã‚²ãƒ¼ãƒ ãƒ©ã‚¤ãƒ•ãƒ¬ãƒ™ãƒ«ã‚¢ãƒƒãƒ—
    url: https://twitter.com/G_OVER_N_GAME
  CS_engineerSA:
    image_url: /images/actors/CS_engineerSA.jpg
    name: Yamazoe Haruki
    url: https://twitter.com/CS_engineerSA
author: FORTE
description: aozora.fmã¯ä»•äº‹ã‚„è¶£å‘³ã®æ¥½ã—ã•ã‚’å…±æœ‰ã™ã‚‹é›‘è«‡ç³»Podcastã§ã™ã€‚
description_rss: aozora.fmã¯ä»•äº‹ã‚„è¶£å‘³ã®æ¥½ã—ã•ã‚’å…±æœ‰ã™ã‚‹é›‘è«‡ç³»Podcastã§ã™ã€‚ãƒãƒƒãƒ‰ã‚­ãƒ£ã‚¹ãƒˆã®æ›¸ãèµ·ã“ã—ã‚µãƒ¼ãƒ“ã‚¹ã€ŒLISTENã€ã¯ã“ã¡ã‚‰ https://listen.style/p/aozorafm?bXdsUTvS
description_long: ä»•äº‹ã‚„è¶£å‘³ã®æ¥½ã—ã•ã‚’å…±æœ‰ã™ã‚‹é›‘è«‡ç³»Podcastã§ã™ã€‚aozora.fmã¯ã‚²ã‚¹ãƒˆã•ã‚“ã‚’å‹Ÿé›†ã—ã¦ã„ã¾ã™ã€‚ã„ã¾æ¥½ã—ã‚“ã§ã„ã‚‹ã“ã¨ã‚’èªã‚ŠãŸã„!Podcastæ¥½ã—ãã†ã ã‹ã‚‰å‡ºãŸã„!ã¨ã„ã†æ–¹ã€ãŠæ°—è»½ã«<a href="https://twitter.com/FORTEgp05" target="_blank">@FORTEgp05</a>ã‹<a target="_blank" href="https://docs.google.com/forms/d/e/1FAIpQLSfR5ZjmZf2N5hr53SR_Q5yB6d02VtgFdNgnMFgcUwW049OGDg/viewform">ãŠä¾¿ã‚Šãƒ•ã‚©ãƒ¼ãƒ </a>ã¾ã§é€£çµ¡ãã ã•ã„ã€‚
email: fortegp05@hotmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-109580420-3
hashtag: aozorafm
itunes_podcast_url: https://fortegp05.github.io/aozorafm/feed.xml
keywords: podcast,ãƒãƒƒãƒ‰ã‚­ãƒ£ã‚¹ãƒˆ,ITã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢,è¶£å‘³,æ¥½ã—ã„ã“ã¨,æ¥½ã—ã‚€,
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: aozora.fm
url: https://fortegp05.github.io/aozorafm/
foo: hoge
supporter_ids:
  - MzRyuKa
  - yahsan2
  - goodengineer7
  - mamehacker
  - uutan1108
supporters: 
  MzRyuKa:
    image_url: /images/supporters/MzRyuKa.PNG
    name: ã¿ãšã‚Šã‚…
    url: https://twitter.com/MzRyuKa
  yahsan2:
    image_url: /images/supporters/yahsan2.jpg
    name: ã¿ã‚„ã‚‚ã¨
    url: https://twitter.com/yahsan2
  goodengineer7:
    image_url: /images/supporters/goodengineer7.jpg
    name: S(ã‚¨ã‚¹)
    url: https://twitter.com/goodengineer7
  mamehacker:
    image_url: /images/supporters/mamehacker.jpg
    name: ã¾ã‚ãƒãƒƒã‚«ãƒ¼
    url: https://twitter.com/mamehacker
  uutan1108:
    image_url: /images/actors/uutan1108.jpg
    name: ã†ãƒ¼ãŸã‚“
    url: https://twitter.com/uutan1108
info_author_ids:
  - info1
  - info2
  - info3
  - info4
  - info5
info_author:
  info1:
    title: aozora.fmã§ã¯ã‚²ã‚¹ãƒˆã‚„ãŠä¾¿ã‚Šã‚’å‹Ÿé›†ä¸­!
    content: ãƒªãƒ³ã‚¯å…ˆã®ãƒ•ã‚©ãƒ¼ãƒ ã‹ã‚‰é€ã‚Œã¾ã™!
    url: https://docs.google.com/forms/d/e/1FAIpQLSfR5ZjmZf2N5hr53SR_Q5yB6d02VtgFdNgnMFgcUwW049OGDg/viewform
    img: https://fortegp05.github.io/aozorafm/images/artwork.jpg
  info2:
    title: å¼Šã‚µãƒ¼ã‚¯ãƒ«ã€Œaozora Projectã€ã®æŠ€è¡“åŒäººèªŒã¯ã“ã¡ã‚‰!
    content: ãƒªãƒ³ã‚¯å…ˆã«ä¸€è¦§ã‚ã‚Šã¾ã™!æ—¢åˆŠã‚‚ã‚ˆã‚ã—ã!
    url: https://fortegp05.hatenablog.com/entry/2024/05/25/161409
    img: https://cdn.image.st-hatena.com/image/scale/871ce3d824084266f87aceb7c672d6aaa02532dc/backend=imagemagick;version=1;width=1300/https%3A%2F%2Fcdn-ak.f.st-hatena.com%2Fimages%2Ffotolife%2Ff%2Ffortegp05%2F20250528%2F20250528184219.png
  info3:
    title: PIXIV FANBOXã§ã‚‚æ”¯æ´å‹Ÿé›†ä¸­!
    content: æœˆé¡åˆ¶ã§æ§‹ã‚ãªã„ã¨ã„ã†æ–¹ã¯æ˜¯éãƒªãƒ³ã‚¯å…ˆã‹ã‚‰!
    url: https://fortegp05.fanbox.cc
    img: https://fortegp05.github.io/aozorafm/images/noimages.jpg
  info4:
    title: OFUSEã§ã‚‚æ”¯æ´å‹Ÿé›†ä¸­!
    content: æœˆé¡ã§ã¯ãªã1å›ã ã‘æ”¯æ´ã—ãŸã„æ–¹ã¯ã“ã®ãƒªãƒ³ã‚¯å…ˆã¸!
    url: https://ofuse.me/fortegp05
    img: https://fortegp05.github.io/aozorafm/images/noimages.jpg
  info5:
    title: ITã‚¨ãƒ³ã‚¸ãƒ‹ã‚¢ã®ãŠä»•äº‹ã‚’å‹Ÿé›†ä¸­!
    content: è©³ç´°ã‚„é€£çµ¡å…ˆã¯ãƒªãƒ³ã‚¯å…ˆã®ãƒ–ãƒ­ã‚°è¨˜äº‹ã‹ã‚‰ãŠé¡˜ã„ã—ã¾ã™!
    url: https://fortegp05.hatenablog.com/entry/2024/08/18/191629
    img: https://fortegp05.github.io/aozorafm/images/noimages.jpg
